### ISSUE TITLE
multiline comments

### ISSUE THREAD

**Issue by 2mol** [aisamanra/config-ini#19]
Hi!

It seems hacky to specify comments that span more than one line. Two naive attempts fail:
If I insert "\n" into the comment string, then the serialization would break at that spot, but not insert another "# "

If I would just add another `& comment [...]` combinator, then the last one is taken and the first is ignored.

It works in the end by not only breaking with newline, but also adding "# " manually.

To illustrate with the example from the docs:

```
configParser' :: IniSpec Config ()
configParser' = do
  section "NETWORK" $ do
    cfHost .=  field "host" string
      & comment ["The desired hostname\n# some other comment line:"]
```

**Comment by aisamanra** [comment]
Ah! I don't think I explained this well in the docs, but the reason the argument to `comment` is a list is specifically to support multi-line comments. So the intended way of adding a multi-line comment would be with

```
configParser' :: IniSpec Config ()
configParser' = do
  section "NETWORK" $ do
    cfHost .=  field "host" string
      & comment ["The desired hostname", "some other comment line:"]
```

I think in addition to documenting that better I should also implement support for multiple `comment` combinators, because it seems like something which might work, and I might as well build the library to support that.
