### ISSUE TITLE
Sections with all optional fields could themselves be optional

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/config-ini#5]
Let's say I specify a section in my config parser (`bidir`), and I specify that all of the fields to appear in that section have default values. Right now, it is only legal to omit the options but not the section header, so a legal config that falls back to all defaults must look like
```
[section]
```
but I'd love it if I could also omit the section header, too.

**Comment by aisamanra** [comment]
85ac32c has introduced `sectionOpt` for this reason. Right now, it still serializes the same way, so I'm going to close this once I've implemented that.

**Comment by aisamanra** [comment]
For documentation:  instead of `sectionOpt`, the optionality of sections now has to do with whether all the fields in a section are themselves optional. So the only way to create a section is with `section`, but if everything in a section is optional, then we can safely skip a section in parsing and in serialization.
