### ISSUE TITLE
emitIniFile produces output with redundant newlines

### ISSUE THREAD

**Issue by jtdaugherty** [aisamanra/config-ini#9]
Observed behavior: use of `emitIniFile` results in output that has two newlines per line.

Expected behavior: one newline per line.

```
> emitIniFile defaultConfig parseConfig
"[section]\n\nfoo=1\n\nbar=2\n\n..."
```

**Comment by jtdaugherty** [comment]
This appears to be fixable by changing
```
vComments = BlankLine <| mkComments (fdComment descr)
```
to
```
vComments = mkComments (fdComment descr)
```
in `toSection`, but I don't know if that's the right thing to do.

**Comment by aisamanra** [comment]
I think my intention there had been that I wanted comments to have extra "padding" around them, but that should be opt-in by the user (by, say, adding an empty string with the `comments` function) rather than a default, so yes, that is the right change. I've gone ahead and done that in the bidir branch with 37404dc.

**Comment by jtdaugherty** [comment]
Thanks!
